### ISSUE TITLE
nmap plugin not registering any  information only regular port open or close

### ISSUE THREAD

**Issue by ChrisFernandez** [infobyte/faraday#102]
when using info gathering options like -A and a output that has actually daemon version like Apache - version  etc.. or SMB if is vulnerable or not is not been entered in the GUI nor the WEB UI.. such is missing all the power of nmap and lowers it to a simple port mapper.. there is no point of having a nmap plugin if is not going to record the output from some of its flags and his nsa scripts output.

**Comment by binkybear** [comment]
Are you asking for nmap portion of app to have option to save to file?

**Comment by Ezequieltbh** [comment]
Hi Chris!

At the moment, the nmap plugin parses some of the NSE script, but due to the number of them out there and their XML format, it is quite difficult to support every and each one.
We have plans to get better this plugin, but we dont have any ETA.

Remember also, Faraday is open source! We'd gladly take any contribution regarding NSE scripts.
If you feel like doing it, you can check out the nmap plugin in /plugins/repo/nmap/plugin.py and modify it to parse other NSE scripts.

Contact us, if you need help for this!
Cheers!

**Comment by ChrisFernandez** [comment]
@Ezequieltbh I c,  ok well I just got back from HOPE in NY and heading out today to BsidesLV and Defcon, so when I get back and recover my sanity I will work on adding more nmap NSE parsers..
thanks.

**Comment by fedek** [comment]
@ChrisFernandez 

We will be in Vegas, we will be showcasing faraday in BlackHat, feel free to swing by. Regarding the NSE parsers, our approach is generic:

If the NSE script says Vulnerable: Issue is created as High
The rest is marked as Informational, If it fails will be marked as unclassified.

But NSE parsing should be working, please send us any output if possible to see what happened on your installation

**Comment by Ezequieltbh** [comment]
Any feedback about this issue @ChrisFernandez ?
Thanks...
