### ISSUE TITLE
MetasploitOn failing to start

### ISSUE THREAD

**Issue by itsnotqwerty** [infobyte/faraday#106]
The error message:
>  2016-08-08 09:45:49,011 - faraday.ModelController - INFO - Plugin Started: MetasploitOn
>  2016-08-08 09:45:49,013 - faraday.ModelController - INFO - Plugin Ended: MetasploitOn

The error message repeats until I shut down Faraday.

Plugin options:
> Enable: 1
> Database: msf
> Wordspace: %%
> Server: 127.0.0.1
> User: msf
> Password: [It's the correct password, I checked]
> Port: 5432 [Where postgresql is running]

**Comment by joaquinlpereyra** [comment]
@itsnotqwerty Hi! Unfortunately, the metasplot online plugin is not working at the moment, but will be fixed in the next release, coming up in just a few days! 

The message you get, though, is completely normal: when activated, the plugin starts and ends in a loop until you disable it or close Faraday. That's how it keep track of changes in the database.

**Comment by itsnotqwerty** [comment]
Oh, okay! Thank you. I was pretty worried that I had broke it, and was trying everything to fix it. I couldn't find anything about it so I posted it here.
