### ISSUE TITLE
gtk and qt3 viersion

### ISSUE THREAD

**Issue by jorge-1** [infobyte/faraday#126]
Then I`m view video about faraday, faraday start with qt3 gui. many features from it, not exist in gtk version. Example: context me nu on host, view hosts and services in on interface tree

**Comment by joaquinlpereyra** [comment]
@jorge-1 The tree is gone on GTK due to performance issues when dealing with big workspaces. Nevertheless, you can click on a host and get all the information you had on the QT3 tree 

Are there other features you seem to be lacking on GTK? Apart from notes/credentials, we'll be adding support for those soon. These few months have been a *big* turning point for Faraday, and some things were left a little behind so as to advance with exciting, backend stuff (our new server, for example: you can now have workspaces of 200k hosts, and the GTK interface will load them in... 3 seconds!. It took more than an hour before to load such workspaces).
