### ISSUE TITLE
the sip module implements API v9.0 to v9.2 but the qt module requires API v8.1

### ISSUE THREAD

**Issue by metasecdev** [infobyte/faraday#13]
I am getting this error with a fully updated Kali x64 instance when starting 

[+] Starting faraday IDE
[*] QTconfig in place
[*] Running under plugin development mode!
[-] Deleting old user directory: /root/.faraday
[+] Creating user directory: /root/.faraday
[*] Loading Plugins
[*] Using images/icons set from user
[*] Using custom user configuration
[*] Cleaning up
[+] Setting up for: x86_64 on Linux
[+] Using python2.7 to run faraday.
2014-07-21 10:08:31,678 - CouchdbManager - DEBUG - Initializing CouchDBManager for url [None]
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    main(sys.argv)
  File "main.py", line 76, in main
    main_app = MainApplication(args)
  File "/opt/faraday-dev/model/application.py", line 62, in __init__
    args.gui)
  File "/opt/faraday-dev/gui/gui_app.py", line 16, in create
    from gui.qt3.application import GuiApp
  File "/opt/faraday-dev/gui/qt3/application.py", line 13, in <module>
    import qt
RuntimeError: the sip module implements API v9.0 to v9.1 but the qt module requires API v8.1

both PyQt and sip are at

sip 4.14.2
PyQt4 4.9.6

**Comment by f-amato** [comment]
Could you please test it with the last version of Faraday? We did a lot of changes in the Faraday installation process
Best

**Comment by noviska** [comment]
i have problem install couchdb in kalilinux, any suggestions?

**Comment by f-amato** [comment]
Could you please provide a error log or more information?
What version of kali are you trying on?
Are you running install.sh ?
Best

**Comment by noviska** [comment]
root@SGI-ASIA:~# uname -a 
Linux SGI-ASIA 3.18.0-kali3-amd64 #1 SMP Debian 3.18.6-1~kali2 (2015-03-02) x86_64 GNU/Linux

when i try to install apt-get install couchdb repo can't find couchdb, i forget to capture because after i upgrade the dependecies have some error on kernel, the menu on kali linux missing so now re-install the kali. Thank u f-amato

**Comment by noviska** [comment]
any suggestion for reporsitory kali linux?

**Comment by f-amato** [comment]
You should have the following repositories:

root@kali:~# cat /etc/apt/sources.list
deb http://http.kali.org/kali sana main contrib non-free
deb-src http://http.kali.org/kali sana main contrib non-free
deb http://security.kali.org/kali-security sana/updates main contrib non-free
deb-src http://security.kali.org/kali-security sana/updates main contrib non-free

**Comment by noviska** [comment]
yup i have already using this repo but still can't find couchdb. may i must use  repository from debian?

**Comment by f-amato** [comment]
I'm pretty sure that you have problem with you Kali.
Are you installing Faraday from the git?
Could you please send us a log of ./install.sh output?

**Comment by noviska** [comment]
here this error log :

W: Ignoring Provides line with DepCompareOp for package libjpeg62
W: Ignoring Provides line with DepCompareOp for package php-psr-http-message-implementation
W: Ignoring Provides line with DepCompareOp for package php-psr-log-implementation
W: Ignoring Provides line with DepCompareOp for package php-math-biginteger
W: Ignoring Provides line with DepCompareOp for package pypy-cffi
W: Ignoring Provides line with DepCompareOp for package pypy-cffi-backend-api-max
W: Ignoring Provides line with DepCompareOp for package pypy-cffi-backend-api-min
W: Ignoring Provides line with DepCompareOp for package python-cffi-backend-api-max
W: Ignoring Provides line with DepCompareOp for package python-cffi-backend-api-min
W: Ignoring Provides line with DepCompareOp for package python3-cffi-backend-api-max
W: Ignoring Provides line with DepCompareOp for package python3-cffi-backend-api-min
W: You may want to run apt-get update to correct these problems
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libglib2.0-0 : Recommends: xdg-user-dirs but it is not going to be installed
                Breaks: glib-networking (< 2.33.12) but 2.32.3-1 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Downloading/unpacking couchdbkit==0.6.5 (from -r requirements.txt (line 1))
  Downloading couchdbkit-0.6.5.tar.gz (81Kb): 81Kb downloaded
  Running setup.py egg_info for package couchdbkit
    
    warning: no files found matching '*' under directory 'docs'
Downloading/unpacking mockito==0.5.1 (from -r requirements.txt (line 2))
  Downloading mockito-0.5.1.tar.gz
  Running setup.py egg_info for package mockito
    
Downloading/unpacking whoosh==2.5.5 (from -r requirements.txt (line 3))
  Downloading Whoosh-2.5.5.tar.gz (964Kb): 964Kb downloaded
  Running setup.py egg_info for package whoosh
    
    warning: no files found matching '*.txt' under directory 'tests'
    warning: no files found matching '*.txt' under directory 'benchmark'
    warning: no files found matching '*.txt' under directory 'docs'
    warning: no files found matching '*.txt' under directory 'files'
    warning: no files found matching '*.py' under directory 'files'
    warning: no files found matching '*.jpg' under directory 'files'
Downloading/unpacking argparse==1.1 (from -r requirements.txt (line 4))
  Downloading argparse-1.1.zip (151Kb): 151Kb downloaded
  Running setup.py egg_info for package argparse
    
Requirement already satisfied (use --upgrade to upgrade): IPy==0.75 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Downloading/unpacking restkit==4.2.2 (from -r requirements.txt (line 6))
  Downloading restkit-4.2.2.tar.gz (1.3Mb): 1.3Mb downloaded
  Running setup.py egg_info for package restkit
    
Downloading/unpacking requests==2.7.0 (from -r requirements.txt (line 7))
  Downloading requests-2.7.0.tar.gz (451Kb): 451Kb downloaded
  Running setup.py egg_info for package requests
    
Downloading/unpacking tornado==3.2 (from -r requirements.txt (line 8))
  Downloading tornado-3.2.tar.gz (400Kb): 400Kb downloaded
  Running setup.py egg_info for package tornado
    
Downloading/unpacking flask==0.10.1 (from -r requirements.txt (line 9))
  Downloading Flask-0.10.1.tar.gz (544Kb): 544Kb downloaded
  Running setup.py egg_info for package flask
    
    warning: no files found matching '*' under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'examples'
    warning: no previously-included files matching '*.pyo' found under directory 'examples'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/_themes/.git'
Downloading/unpacking colorama==0.3.2 (from -r requirements.txt (line 10))
  Downloading colorama-0.3.2.tar.gz
  Running setup.py egg_info for package colorama
    
Downloading/unpacking psycopg2==2.5.4 (from -r requirements.txt (line 12))
  Downloading psycopg2-2.5.4.tar.gz (682Kb): 682Kb downloaded
  Running setup.py egg_info for package psycopg2
    
    Error: You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.
    
    Complete output from command python setup.py egg_info:
    running egg_info

creating pip-egg-info/psycopg2.egg-info

writing pip-egg-info/psycopg2.egg-info/PKG-INFO

writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt

writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt

writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'

warning: manifest_maker: standard file '-c' not found



Error: You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.



----------------------------------------
Command python setup.py egg_info failed with error code 1 in /root/Desktop/faraday-master/build/psycopg2
Storing complete log in /root/.pip/pip.log
You can now run Faraday, enjoy!

**Comment by f-amato** [comment]
Did you try to install using apt-get install python-faraday?
Could you please send us the information inside /etc/debian_version?
The output of the installation is missing the first part could you please send us the complete output.
Best
