### ISSUE TITLE
Dont Show Result

### ISSUE THREAD

**Issue by N4ckHcker** [infobyte/faraday#206]
Hello. Sorry for my english.. yesterday i open faraday for first time.. i start server and client after that
i make a new workspace and i scan a site to test it.. i used wpscan > wpcsan --url site --enumerate p
i open the dashboard in web nothing not result show.. and site have vul.. can you help me ?

**Comment by WinnaZ** [comment]
Hello N4ckHcker,
Sorry for the late reply, 
Yeah of course, but i need a bit more info to understand the issue here,
Does the terminal where you are running the Server show any Error message?
How did use the tool?
I mean, did you use the GTK interface to do the scan directly, or did you do the scan separately and then imported the xml file?
Hope to hear from you soon!

**Comment by N4ckHcker** [comment]
Dont Have Error... all is fine. Just dont show results :/

**Comment by WinnaZ** [comment]
hey N4ckHcker,
Yes, there's is a bug in that specific plugin.
We added that fix to our road map.
Thanks for the feedback.

**Comment by llazzaro** [comment]
Hi!
We updated the wpscan plugin in the last release v3.7.0.
Try to update faraday and also wpscan.
Thanks!
