### ISSUE TITLE
Faraday Installation error running ./faraday-server.py

### ISSUE THREAD

**Issue by GypsyCosmonaut** [infobyte/faraday#215]
System information:
Linux kali 4.12.0-kali1-amd64 #1 SMP Debian 4.12.6-1kali5 (2017-08-25) x86_64 GNU/Linux

When I clicked Faraday to run it, it gave me an error that the connection can't be made, retry connection, exit, so I searched upon internet and couldn't understand anything after trying a bunch of solutions for editing configuration files I edited the files `/etc/couchdb/local.ini` and `~/.faraday/config/server.ini`

I uncommented the "port" and "bind_address" under [httpd] in `/etc/couchdb/local.ini`
and my `~/.faraday/config/server.ini` has the following 

```
[faraday_server]
port=5985
bind_address=localhost

[ssl]
port=6985
certificate=
keyfile=
keyfile_pwd=''

[couchdb]
host=localhost
ssl_port=6984
user=
password=
protocol=http

```

So, I downloaded the project from github

I followed the following steps in my `~/`

```

git clone https://github.com/infobyte/faraday.git faraday-dev

cd faraday-dev

./install.sh

./faraday-server.py

```

Now, this is where I get error, 

```

faraday-server.server.couchdb - WARNING - Reports database couldn't be uploaded. You need to be an admin to do it

faraday-server.server.importer - ERROR - CouchDB is not running at http://localhost:5984. Check faraday-server's configuration and make sure CouchDB is running

```

What do I do to fix this error so that when I run the next command `./faraday.py` , it runs Faraday properly. I have never used Faraday before, but I really am interested in using it, but both out of the box installation and installation through following the Faraday guide gives error.

**Comment by arismelachroinos** [comment]
Same issue here.

**Comment by WinnaZ** [comment]
Give a look at our official documentation here: https://github.com/infobyte/faraday/wiki/Installation-Community
on how to properly install Faraday, cause it seems like you're missing a few steps.

Also that error message i'm seeing says that the problem is that couchdb is not running, it's a necessary tool for Faraday to work (for now at least).
So, first of all check if it's running,
if you are having trouble installing couch here you have a wiki that should help you:
https://github.com/infobyte/faraday/wiki/Installation-CouchDB 

let us know how it goes,
and have a nice day :)
