### ISSUE TITLE
Linux (Ubuntu) installation procedure error/Report uploading issue

### ISSUE THREAD

**Issue by RicForesight** [infobyte/faraday#220]
Hello,

I was trying to install the server version of Faraday and followed the instructions provided on https://github.com/infobyte/faraday/wiki. However, when I fun the ./faraday-server.py I got a dependency error (ImportError: cannot import name IncompleteRead). After some googling, I discovered this was a pip error as the new version of pip does not include this particular module. The solution which I found on the internet is to uninstall the 'request' package and the program runs. To remove I used the following command `rm -rf /usr/local/lob/python2.7/dist-packages/request*.`

The new problem I have, maybe due to this deletion is that I cannot import reports to Faraday. I tried four different modules, Metasploit, Masscan, Burp and Maltego. I was unsuccessful with all of them. I followed the standard procedure to create the XML reports on Metasploit, Burp, and Masscan, and I used a csv report for maltego. Faraday correctly identified the plugins but failed to import any of the data in the files.

Any help would be appreciated.

**Comment by WinnaZ** [comment]
Hi there RicForesight,
We are sorry for the late reply, last week was crazy with hosting the EkoParty.
Some questions,
Did you do a quick install or did you go to to our Installation on Community page on the wiki (https://github.com/infobyte/faraday/wiki/Installation-Community)
it sounds like you are having problem with out sistem depencencies check out : https://github.com/infobyte/faraday/wiki/Installation-Community#installing-system-dependencies

In any case, please send over the error message you get when trying to do the import. Otherwise it very difficult to troubleshoot.
Cheers!

**Comment by RicForesight** [comment]
Thank you for your response, I instead used a kali instance with the python-faraday package and so far its working.
