### ISSUE TITLE
Can not update SERVICE information after second import

### ISSUE THREAD

**Issue by s0i37** [infobyte/faraday#247]
Please search the [Wiki](https://github.com/infobyte/faraday/wiki) for a solution before posting a ticket. Use the <strong>“New Support Request”</strong> button to the right of the screen to submit a ticket for technical support.

## Issue Type
 - Feature Idea

## Faraday version
Faraday v2.7.1

## Steps to reproduce
I noticed, what service name and service description don't change after repeated import. Also port status wont change if port closed too. I suppose, what last scan-report is more important when previos. For example, first step is reconnaissance and I get information from shodan. This information may not actualy. The second scan, for example with nmap, will more detailed and a part information of services or ports may change. 

1. 

service samba start
nmap -sS -p 445 127.0.0.1 -oX out.xml
mv out.xml ~/.faraday/report/test/

2. 

nmap -sS -p 445 127.0.0.1 -oX out.xml -sV
mv out.xml ~/.faraday/report/test/

3. 

service samba stop
nmap -sS -p 445 127.0.0.1 -oX out.xml
mv out.xml ~/.faraday/report/test/

## Expected results

I expected to see changing SERVICE name/desc and PORT status after second and third report.

### OS

Provide information on your operating system. Example: 

$ cat /etc/lsb-release 
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

**Comment by WinnaZ** [comment]
Hi  @s0i37,
thank you so much for your feedback, 
as a matter of fact i am already developing some new things regarding problems like this.
I'll keep you updated on this.
Cheers!

**Comment by WinnaZ** [comment]
Hi again  @s0i37,
That is already integrated into Faraday. The thing is it creates a conflict:
![image](https://user-images.githubusercontent.com/24845440/37994523-5868d1d2-3201-11e8-99a1-efd152d60c14.png)
as you are not using GTK you are not seeing the conflicts and cli doesn't resolve it.
We are coding a new option for cli that will have a parameter like: --conflics keep-old / keep-new
For now you're issue will be fixed by just opening gtk to import the xml and resolve conflicts.
Also! The command is as simple as that one you can always just throw it inside gtk terminal and will be automatically uploaded to Faraday.
![image](https://user-images.githubusercontent.com/24845440/37994676-cbaba246-3201-11e8-8d75-4714591b17be.png)
Have a good week!
