### ISSUE TITLE
[Feature Request] Merge findings

### ISSUE THREAD

**Issue by aress31** [infobyte/faraday#288]
A very useful feature that is at the moment missing from Faraday would be the option to merge multiple findings into one. An exmaple would mergind all the SSL/TLS related findings in to a finding covering them all. I am aware that other reporting framework offer this feature. Would be nice to see this implemented in Faraday too.

**Comment by WinnaZ** [comment]
hi again,
Yeah we get this feature requested a lot.
We are certainly looking into it.
Althought the logic is not that simple, you can't just "merge" them. They are different vulns by different tool. Maybe instead of merging something like custom grouping would be more handfull.
We'll keep you updated and thank you for the feedback!

**Comment by daniejstriata** [comment]
Grouping similar vulnerabilities from various sources can be beneficial. Either from different tools or the same tool but 1 finding could be on the internal IP and the other on the external.

**Comment by llazzaro** [comment]
Hi,

We are working on a solution to this problem. We are close to release it on the next version, stay tuned!
