### ISSUE TITLE
Could not connect to PostgreSQL.

### ISSUE THREAD

**Issue by swarupsro** [infobyte/faraday#340]
```
➜  python-faraday python manage.py initdb
/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:774: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  'Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. '
This script will  create a new postgres user  and  save faraday-server settings (server.ini). 
WARNING: Role faraday_postgresql already exists, skipping creation 
Could not find connection string.
Please configure [database] section with correct postgresql string. Ex. postgresql+psycopg2://faraday_postgresql:PASSWORD@localhost/faraday
➜  python-faraday 

```

**Comment by llazzaro** [comment]
Hi,
You already have the role faraday_postgresql in postgresql ans it seems that your server.ini is missing the credentials.
You can reset the password from postgresql of the role faraday_postgresql using the query:

```
ALTER ROLE faraday_postgresql WITH PASSWORD 'databasesecretpassword';
```

then you will need to configure the server.ini manually on the database section:

```
[database]
connection_string =postgresql+psycopg2://faraday_postgresql:databasesecretpassword@database_host/faraday
```

Remember to change database_host with the ip of the database (usually localhost).

Ther first time you execute python manage.py initdb it will create everything and configure automatically the server.ini. initdb failed since it found the database role faraday_postgresql.
Another option is to drop the role faraday_postgresql, but this could make you lose information and it is not the recommended way.

Just in case another github user comes to this ticket, never delete the .faraday directory. If you really need to delete .faraday directory make sure you make a backup. Initdb generates configurations on the database using random password and it will be only saved on server.ini (if you delete this file you will lose the database password)

Thanks!

**Comment by montive** [comment]
Hi.

How did it go?

Cheers.
