### ISSUE TITLE
Unable to start client on ubuntu 18.04 server 

### ISSUE THREAD

**Issue by BlackJebus** [infobyte/faraday#342]
Server is working, and i can import each of the reports one by one. but when i have tried to run the client to auto import (or mass import) it will not start

this is on a 18.04 Server install, and Iv made sure i ran then 
pip2 install vext
pip2 install vext.pygtk
on install (iv also re run the client install process just to make sure im right. 
iv also attached the user.xml here 
[user_xml.txt](https://github.com/infobyte/faraday/files/2853276/user_xml.txt)

[requirements_frez.txt](https://github.com/infobyte/faraday/files/2853279/requirements_frez.txt)

## Faraday version
Faraday v3.5.0

## Component Name
faraday client unable to start 

If you know where the problem lays indicate it:
/Console/ CLIENT

## Steps to reproduce

[requirements_frez.txt](https://github.com/infobyte/faraday/files/2853260/requirements_frez.txt)
python2 faraday.py 

## Expected results

Faraday Client to start

### Debugging tracebacks (current results)

Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
2019-02-11 21:53:29,761 - faraday.launcher - INFO [faraday.py:254 -         startFaraday() ]  Main application ExceptHook enabled.
2019-02-11 21:53:29,761 - faraday.launcher - INFO [faraday.py:257 -         startFaraday() ]  Starting main application.

* Faraday UI is ready
Point your browser to:
[http://10.38.5.1:5985/_ui]

2019-02-11 21:53:29,762 - faraday - INFO [api.py:118 -      _setUpAPIServer() ]  XMLRPC API server configured on ('localhost', 9876)
2019-02-11 21:53:29,768 - faraday - INFO [api.py:66 -            startAPIs() ]  REST API server configured on ('localhost', 9977)
Unable to init server: Could not connect: Connection refused

(faraday.py:1575): Gtk-WARNING **: 21:53:29.771: cannot open display:
root@temp:~/faraday-dev# (located at *$HOME/.faraday/logs/*).

Please attach the result of:

pip freeze > requirements_freeze.txt

### OS

this is a server install no GUI 

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04"

**Comment by montive** [comment]
Hi there.

Are you running the Client from the same box where the Server is running or from a remote box?

Cheers.

**Comment by BlackJebus** [comment]
Hi
Yea on the same server.  im running it headless. (using SSH to start stop Faraday) and was under the impression that the Client will MAS import the report files. )

**Comment by montive** [comment]
Hi.
As I can see here:

* Faraday UI is ready
  Point your browser to:
  [http://10.38.5.1:5985/_ui]

You are try to connect to a remote server. If this is the case, remember to expose the server (see https://github.com/infobyte/faraday/wiki/Installation-Community#exposing-the-server).

Once you have exposed it, restart the server and run the client with the right configuration (see https://github.com/infobyte/faraday/wiki/Installation-Community#configuration-1)

**Comment by WinnaZ** [comment]
Hey there @BlackJebus ,
Did what Javier say work out?
Cheers

**Comment by BlackJebus** [comment]
Sorry my last week has been hectic,  

The Client and Server are installed on the same server 
i have set the bind address to 0.0.0.0 but the client still has issues starting 


root@template_changeme:~/.faraday/config# nano server.ini
  GNU nano 2.9.3                      server.ini

[faraday_server]
port = 5985
bind_address = 0.0.0.0
websocket_port = 9000
secret_key = BLANKEDOUT
[ssl]
port = 6985
certificate =
keyfile =

[couchdb]
host = localhost
port = 5984
ssl_port = 6984
user =
password =
protocol = http

**Comment by BlackJebus** [comment]
i also reset this line 
user.xml
<api_url>http://127.0.0.1:5985</api_url>

user.xml
<api_url>http://10.38.5.1:5985</api_url>  <-- Server IP address 

Still dose not work.

**Comment by montive** [comment]
Hi there. Is it possible that you are using a firewall that is preventing the server to connect to Faraday server?

**Comment by Selbstmord-Schafskult** [comment]
I'm adding some virtual machines right now and am rebuilding from the kernel up, with a distribution other than Kali. It's not as stable as I thought. Backtrack was more stable, in my opinion. The memory seems to get easily corrupted by various things.. It's secure, but too "sensitive" for lack of a better word. I'm excited about adding Faraday to my methodology though. I've seen it work before a long time ago & was impressed.
I'm designing a collaborative system for finding human traffickers and their victims. (mostly children) Combining the right data sets, from a variety of sources and finding others with the same drive who understand that no form of automation filtering will ever replace the human factor. All that's needed is a small amount of data. There's myself and 2 others thus far. Combining tools like Maltego, Shodan, u openvas, eyewitness, photo DNA, project VIC & a MASSIVE database collection, along with some hardware that I needed to design (because it doesn't exist and I need added capabilities. In addition to what's available) hardware hacking is actually what I'm best at. I'm hoping to get the most elusive perps... Some of them are on Tor, so there's an added challenge. The only thing I feel is missing is some form of live conference call/realtime, cooperative implementation. thumbs up to Faraday btw. If you have any suggestions or would like to participate, please hmu.

-------- Original Message --------

**Comment by BlackJebus** [comment]
> Hi there. Is it possible that you are using a firewall that is preventing the server to connect to Faraday server?

yea just checked UFW status 

inactive

so as far as i can see it shouldnt be running

**Comment by montive** [comment]
Ok. I think that you sent us the requirementes_frez.txt incomplete. I can only see the requirements from letter p to z. Please, send me the complete freeze. 
Also, did you install the requirements for the Client? These are installed by running `pip2 install -r requirements.txt -U`

**Comment by whoami-ru** [comment]
Hi. I have troubles with connect from remote client to server, may be you can help me.
I checked that the firewall is off on server, and  port 9977 is listening, availability betwen server and client hosts (with telnet), faraday service is running.
There is no file server.ini, but i change file default.ini with my server IP.
On server i run "faraday-client --gui=no-gui" and trying to connect from client, but in terminal it's still writing "[!] Using default configuration 127.0.0.1:9977"
i also trying to change ./faraday/client/zsh/faraday-terminal.zsh but it doesn't help too.

**Comment by cript0nauta** [comment]
Hi @whoami-ru! Port 9977 is used internally by the Faraday client, and isn't related to the Faraday server, that listens in port 5985.

Could you try running the `faraday-client --login` command? That should ask for the Faraday Server URL (http, port 5985), and your username and password. After a successful login, the client should be running correctly.

**Comment by whoami-ru** [comment]
> 
> 
> Hi @whoami-ru! Port 9977 is used internally by the Faraday client, and isn't related to the Faraday server, that listens in port 5985.
> 
> Could you try running the `faraday-client --login` command? That should ask for the Faraday Server URL (http, port 5985), and your username and password. After a successful login, the client should be running correctly.

HI. It still doesn't work. service is running but port 5985 is closed. 
![pic2](https://user-images.githubusercontent.com/60693100/73906974-f0e19580-48ce-11ea-8ee5-58dba47acb6e.PNG)
I think the problem is that the service is running on localhost(pict). 
![pic](https://user-images.githubusercontent.com/60693100/73906501-43ba4d80-48cd-11ea-837c-75b03c737821.PNG)
Port 9977 i opened with netcat and when i try to connect it works properly

**Comment by cript0nauta** [comment]
@whoami-ru here is an explanation to make Faraday Server listen in `0.0.0.0`: https://github.com/infobyte/faraday/wiki/How-to-run-Faraday#connect-to-faraday-server-from-a-remote-machine

**Comment by whoami-ru** [comment]
@cript0nauta thank you! i changed file server.ini in wrong directory, now it's ok!
