### ISSUE TITLE
FARADAY v3.8 (PRO)  - Could not connect to PostgreSQL. 

### ISSUE THREAD

**Issue by CorpOfHack** [infobyte/faraday#366]
## Issue Type
 - Bug Report

## Faraday version

**v 3.8**  *(commercial  version)*

## Steps to reproduce

`./faraday-server`

### Debugging tracebacks (current results)
```
Could not connect to PostgreSQL.
Please check: 
  * if database is running 
  * configuration settings are correct. 

For first time installations execute: 

  faraday-manage initdb


2019-06-20 08:37:38,606 - faraday-server.__main__ - WARNING {MainThread} [start_server.py:160 - check_alembic_version() ]  You are using an unknown schema version. If you are a developer, this probably happened because you used branch with a schema migration not merged yet. If you are a normal user, consider reporting this bug back to us                                          
2019-06-20 08:37:38,610 - faraday-server.__main__ - ERROR {MainThread} [start_server.py:130 - check_postgresql() ] 


```
#### The error:
![Screenshot](https://content.screencast.com/users/Hacker1/folders/Jing/media/333f40f2-2394-4295-b9d6-a9ef0f2bdbde/2019-06-20_1553.png)

#### Posgresql Is currently runned

![image](https://user-images.githubusercontent.com/16857976/59851630-c65dbf00-9375-11e9-904d-968fea5c0deb.png)

## Environment information
OS **Kali-Linux**
psql **(PostgreSQL) 10.3 (Debian 10.3-2)**
Python **2.7.14+**

### OS

**$ cat /etc/lsb-release**
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

**Comment by CorpOfHack** [comment]
If I am changing faraday_postgresql credentials and adding connection string to **####server.ini####** I will receive a new issue related to faraday-manage util, because it uses preinstalled credentials for faraday-postgresql user. But I am not able to find this config file where the password is located in.

**Comment by CorpOfHack** [comment]
Temporary fixed via adding postgresql user with permissions to manage faraday DB and putting  credentials to the connection string in **server.ini** file.

**Comment by llazzaro** [comment]
Hi,
If you have the commercial version we can arrange a call to help you.
I will like to review your case.
Please check: https://support.faradaysec.com/portal/home 
If you can send us the error of the `initdb` that could be very helpful.
Also we have the `faraday-manage support` command that will create a .zip files with logs to troubleshoot this problem.

Thanks!
Leonardo

**Comment by jfarl** [comment]
They make it impossibly difficult to set up in order to coerce an upgrade to the professional version.
@NotSoEthical you are absolutely correct - The "faraday_postgresql" user and table is successfully initialized on install/first run but the user's password is not disclosed and no database connection string is created in the server.ini file. 
In fact, there's no documented reference to [database] in the .ini file or on their official documentation or FAQs (from what I can see) to even know that it should exist - making debugging near impossible.

**Comment by aenima-x** [comment]
@jfarl If you have problems with the commercial version please contact out support.

We are currently updating the documentation.
Our current version (3.12) runs in python3 so I don't understand the pip2 comment.
Related to the postgres error did you tried to connect with that user from the command line?

If you like open a new issue and explain me your problems.
I dont have any problem running the latest version in OSX

**Comment by jfarl** [comment]
Hey I made a typo in that screenshot above but it doesn't matter. That's not the point. The correct username results in yet **another error** with the initdb command.

You get the honor of "one of those projects" when the documentation and build process is so broken that every conceivable way to building the project fails. A process this bad requiring so much debugging is also bound to result in user error such as above, compounding the issue. - I wonder how many people have sunk an entire evening into building this but ultimately gave up?

Your own dev install guide references pip2 and python2 -- https://github.com/infobyte/faraday/wiki/Development-Installation-OSX

Fix this:
$ pip2 install -r requirements_server.txt -U
$ pip2 install -r requirements.txt -U
to
$ pip install -r requirements.txt -U

$ brew install pygobject3 --with-python@2
to
$ brew install pygobject3

-------------

Normal OSX install: https://github.com/infobyte/faraday/wiki/Install-Guide#macos
$ pip install faradaysec
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/2223444/101289121-24779f80-37c0-11eb-9394-adcd20893fed.png">
Good luck with all that.

Install from git repo instructions are broken:
<img width="492" alt="image" src="https://user-images.githubusercontent.com/2223444/101289220-c1d2d380-37c0-11eb-99f8-c8a3a5420736.png">

Broken link: https://virtualenv.pypa.io/en/latest/userguide/
<img width="483" alt="image" src="https://user-images.githubusercontent.com/2223444/101289263-fa72ad00-37c0-11eb-801f-47697812d944.png">

-------------

In conclusion, I'm not opening another issue because I'm no longer interested in creating a working project. I'm leaving this here as both a warning for wayward travelers and as a lever of work for improvements for your team. I'm already way past the "fail fast" cutoff I set for myself when building a new project - I let myself get carried away because this one seemed promising.
I've sunk enough hours into getting a working version of this product for the point of demoing it to upper management to receive buyin for a purchase agreement. Even Dradis was able to get up and running with some minor config. 

I'm coming from a previous client with a medium sized team where in ~2017 we build a similar in-house pentest platform for pentest tracking and bi-directional Jira sync for SDLC pentesting. The current client does not have the dev resources and I'm not willing to undertake a similar effort for a second time. Hence, looking for some commercial off-the-shelf product.
